[build]
base = "/"
command = "pnpm run packages:build && pnpm run build"
publish = "/playground/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
